export const user = [
  {
    src: 'https://source.unsplash.com/2ShvY8Lf6l0/800x599',
    width: 4,
    height: 3,
    name: 'Name1',
    author: 'Mitarbeiter1',
  },
  {
    src: 'https://source.unsplash.com/Dm-qxdynoEc/800x799',
    width: 1,
    height: 1,
    name: 'Name2',
    author: 'Mitarbeiter1',
  },
  {
    src: 'https://source.unsplash.com/qDkso9nvCg0/600x799',
    width: 3,
    height: 4,
    name: 'Name3',
    author: 'Mitarbeiter1',
  },
  {
    src: 'https://source.unsplash.com/iecJiKe_RNg/600x799',
    width: 3,
    height: 4,
    name: 'Name4',
    author: 'Mitarbeiter2',
  },
  {
    src: 'https://source.unsplash.com/epcsn8Ed8kY/600x799',
    width: 3,
    height: 4,
    name: 'Name5',
    author: 'Mitarbeiter2',
  },
  {
    src: 'https://source.unsplash.com/NQSWvyVRIJk/800x599',
    width: 4,
    height: 3,
    name: 'Name6',
    author: 'Mitarbeiter2',
  },
  {
    src: 'https://source.unsplash.com/zh7GEuORbUw/600x799',
    width: 3,
    height: 4,
    name: 'Name7',
    author: 'Mitarbeiter3',
  },
  {
    src: 'https://source.unsplash.com/PpOHJezOalU/800x599',
    width: 4,
    height: 3,
    name: 'Name8',
    author: 'Mitarbeiter4',
  },
  {
    src: 'https://source.unsplash.com/I1ASdgphUH4/800x599',
    width: 4,
    height: 3,
    name: 'Name9',
    author: 'Mitarbeiter4',
  },
  {
    src: 'https://source.unsplash.com/XiDA78wAZVw/600x799',
    width: 3,
    height: 4,
    name: 'Name10',
    author: 'Mitarbeiter5',
  },
]
